import json
import re
import statistics

from groq import Groq

from config import GROQ_API_KEY, GROQ_MODEL

_client = None


def _get_client():
    global _client
    if _client is None:
        if not GROQ_API_KEY:
            raise RuntimeError("GROQ_API_KEY is not set")
        _client = Groq(api_key=GROQ_API_KEY)
    return _client


LLM_PROMPT = """You are a content-provenance analyst. Read the passage below and judge whether \
it was written by a human or generated by an AI language model.

Consider: generic or overly balanced phrasing, hedging language, uniform sentence rhythm, and \
topic-generic fluency tend to indicate AI generation. Idiosyncratic word choice, uneven pacing, \
and concrete personal detail tend to indicate human writing.

Respond with ONLY a JSON object in this exact shape, no other text:
{{"ai_likelihood": <float between 0.0 and 1.0>, "reasoning": "<one sentence>"}}

Passage:
\"\"\"
{text}
\"\"\"
"""


def get_llm_score(text):
    """Signal 1: LLM-based semantic/stylistic judgment. Returns a 0-1 AI-likelihood float."""
    client = _get_client()
    completion = client.chat.completions.create(
        model=GROQ_MODEL,
        messages=[{"role": "user", "content": LLM_PROMPT.format(text=text)}],
        temperature=0.0,
        max_tokens=200,
    )
    raw = completion.choices[0].message.content.strip()
    match = re.search(r"\{.*\}", raw, re.DOTALL)
    if not match:
        raise ValueError(f"could not parse LLM response: {raw}")
    data = json.loads(match.group(0))
    score = float(data["ai_likelihood"])
    return max(0.0, min(1.0, score))


def _sentences(text):
    parts = re.split(r"(?<=[.!?])\s+", text.strip())
    return [p for p in parts if p]


def _sentence_length_variance_score(text):
    lengths = [len(s.split()) for s in _sentences(text)]
    if len(lengths) < 2:
        return 0.5
    mean_len = statistics.mean(lengths)
    if mean_len == 0:
        return 0.5
    coeff_of_variation = statistics.pstdev(lengths) / mean_len
    # low variation (uniform sentence length) reads as AI-like -> high score
    return max(0.0, min(1.0, 1 - (coeff_of_variation / 0.6)))


def _type_token_ratio_score(text):
    words = re.findall(r"[a-zA-Z']+", text.lower())
    if len(words) < 60:
        # TTR is only a meaningful proxy for lexical diversity past a minimum sample
        # size — short passages naturally have few repeated words regardless of
        # authorship, so treat them as neutral rather than a false human/AI signal.
        return 0.5
    ttr = len(set(words)) / len(words)
    # low lexical diversity reads as AI-like -> high score
    return max(0.0, min(1.0, (0.8 - ttr) / 0.4))


def _punctuation_density_score(text):
    if not text:
        return 0.5
    varied_punct = re.findall(r"[;:\-—…!]", text)
    density = len(varied_punct) / len(text)
    # low density of expressive/varied punctuation reads as AI-like -> high score
    return max(0.0, min(1.0, 1 - (density / 0.02)))


def get_stylometric_score(text):
    """Signal 2: pure-Python structural heuristics. Returns a 0-1 AI-likelihood float."""
    scores = [
        _sentence_length_variance_score(text),
        _type_token_ratio_score(text),
        _punctuation_density_score(text),
    ]
    return sum(scores) / len(scores)
